variable "main_vpc_id" {}
variable "subnet_ids" {}
variable "aws_account_id" {}
variable "site_domain" {}
variable "site_name" {}
variable "site_prefix" {}
variable "s3_region" {}
variable "slack_webhook" {}
variable "launch" {}
variable "ecs_cpu" {}
variable "ecs_memory" {}
variable "snapshot_identifier" {}
variable "cloudfront_aliases" {}
variable "cloudfront_class" {}
variable "hosted_zone_id" {}
variable "waf_enabled" {}
variable "wordpress_subdomain" {}
variable "wordpress_admin_user" {}
variable "wordpress_admin_password" {}
variable "wordpress_admin_email" {}
variable "waf_acl_rules" {}